CREATE TABLE EMP_DDL (
    EMPNO       NUMBER(4)   PRIMARY KEY,
    ENAME       VARCHAR2(10) NOT NULL, 
    JOB         VARCHAR2(9) NOT NULL,
    MGR         NUMBER(4) NOT NULL,
    HIREDATE    DATE DEFAULT SYSDATE,
    SAL         DECIMAL(7,2),
    COMM        DECIMAL(7,2),
    DEPTNO      NUMBER(2) NOT NULL
);

DESC EMP_DDL;

ALTER TABLE EMP_DDL RENAME TO EMP_ALTER;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER MODIFY EMPNO VARCHAR2(5);

DESC EMP_ALTER;

ALTER TABLE EMP_ALTER DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

DROP TABLE EMP_ALTER;

DESC EMP_ALTER;

CREATE INDEX IDX_EMP_SAL ON emp(SAL);

SELECT *
FROM ALL_IND_COLUMNS
WHERE TABLE_NAME = 'IDX_EMP_SAL';

DROP INDEX IDX_EMP_SAL;

-- SCOTT계정에 뷰 생성 권한 부여하기
-- <window+R> -> cmd 검색
-- sqlplus / as sysdba 
-- 아이디 비밀번호 입력
-- grant create view to SCOTT;
